### ISSUE TITLE
Change Months

### ISSUE THREAD

**Issue by j999** [philipehsing/jQuery.Simple-Event-Calendar#1]
Months do not change in demo using previous and next buttons. Viewed in Firefox and IE11

**Comment by philipehsing** [comment]
Hey, i will check that out during this week :)

**Comment by cangoktas** [comment]
any updates? it doesn't change on Chrome either

**Comment by philipehsing** [comment]
the function is not yet commenced and has not had time to start it yet, unfortunately.

**Comment by philipehsing** [comment]
Solved! Check out the new version!
