### ISSUE TITLE
How to force order the days in header, now it change always to show 1st in first box.

### ISSUE THREAD

**Issue by junaidcs** [philipehsing/jQuery.Simple-Event-Calendar#10]
Hi there!
Can you please tell that how can we order the days in header from `Monday to Sunday`, now it change based on month we move to, always to show `1st date` in first box.

Thanks

**Comment by szymko20** [comment]
Please help generate day! I want to always be generated days from Monday to Sunday. Anyone help me?

**Comment by philipehsing** [comment]
https://github.com/philipehsing/jQuery.Simple-Event-Calendar/issues/8
