### ISSUE TITLE
Can I insert event using ajax?

### ISSUE THREAD

**Issue by MohammadTF** [philipehsing/jQuery.Simple-Event-Calendar#11]
I am making an dynamic event calendar for my class project. I insert data through a html form and I get response from PHP and then I use jQuery's append function to append response to <div class='event' id="eventList" >.

PHP response:

&lt;div class="day-event" date-day='2' date-month='12' date-year='2015'  data-number="1"&gt;
			 &lt;a href="javascript:;" class="close fontawesome-remove eventlist-close">&lt;i class="fa fa-close">&lt;/i>&lt;/a&gt;
			  &lt;h2 class="title"&gt;My title&lt;/h2&gt;
			  &lt;p class="date"&gt;2015-05-2016&lt;/p&gt;
			  &lt;label class="check-btn"&gt;
			  &lt;input type="checkbox" class="save" id="save" name="" value=""/&gt;
			  &lt;span&gt;Save to personal list!&lt;/span&gt;
			  &lt;/label&gt;
			&lt;/div&gt;

I append above div to  <div class='event' id="eventList" > and it is appending perfectly. but the event icon is not showing on calendar.

if I am doing it wrong kindly tell me how can I dynamically add events using ajax?

Thanks in advance

**Comment by philipehsing** [comment]
make an ajax call to your php, append the response? Can i have a look on the code?
