### ISSUE TITLE
Calendar date

### ISSUE THREAD

**Issue by Copper57** [philipehsing/jQuery.Simple-Event-Calendar#13]
Hi is it possible to have Monday, Tuesday Wenesday, always at the same place, and have the date number to move when changing month. Like a regular calendar.

Thank You

**Comment by nilankaperera** [comment]
This calendar plugin is really cool if we can fix this week date order from Monday to Sunday.

**Comment by philipehsing** [comment]
https://github.com/philipehsing/jQuery.Simple-Event-Calendar/issues/8

**Comment by snowmoonsoftware** [comment]
Code from #8 incorporated and tweaked here https://github.com/snowmoonsoftware/jQuery.Simple-Event-Calendar
