### ISSUE TITLE
Make calendar always start on Monday (for all months)

### ISSUE THREAD

**Issue by evocreative** [philipehsing/jQuery.Simple-Event-Calendar#15]
Hi,

I need to know if there is a way to make the calendar always show Monday as first day (first column) for ALL months. Right now this only happens for months where day 1 is Monday.

Thanks,

**Comment by philipehsing** [comment]
Please look at closed issues... https://github.com/philipehsing/jQuery.Simple-Event-Calendar/issues/8

**Comment by evocreative** [comment]
Hi,

Thanks, but unfortunately it seems that this solution only works with current default loaded month, when you change to another month, they don't appear correctly. Even, when you go back to the current month, this month doesn't looks correctly.

You can see it [here](http://www.makeupinstitute.cz/)

Thanks,

**Comment by philipehsing** [comment]
Hi, I have not tested the solution.
Do you have any knowledge of jQuery?

Is it any problem that month not starts with monday? 

/ Philip

**Comment by evocreative** [comment]
Hi,

Well, I have some jQuery knowledges, but unfortunatelly not enough to find a solution for this.

Yes, I need to make all months start with monday (even when navigating to next/prev months).

Thanks,

**Comment by evocreative** [comment]
Hi,

I need to be sure if there is a possible solution for this, or I will need to use another different calendar.

Thanks,

**Comment by evocreative** [comment]
This is my current code. With the help of the closed issue #8 response I where able to make the actual month looks correctly, but as I said when going to prev or next month (and even when going back to actual month), they are not being showed correctly:

`
jQuery( document ).ready(function($) {
var calendar = {

	init: function(yearNumber,monthNumber) {

		yearNumber = Number(yearNumber);
		monthNumber = Number(monthNumber);

      calendar.startCalendar(yearNumber,monthNumber);

	},

  startCalendar: function(yearNumber,monthNumber) {

  		yearNumber = Number(yearNumber);
		monthNumber = Number(monthNumber);
   		var mon = 'pon';
		var tue = 'úte';
		var wed = 'stř';
		var thur = 'čtv';
		var fri = 'pát';
		var sat = 'sob';
		var sund = 'ned';

		/**
		 * Get current date
		 */
		var d = new Date();
		var strDate = yearNumber + "/" + monthNumber + "/" + 1;
		var tmpDate = new Date(strDate);
		var firstDay = tmpDate.getDay() - 1;
		var firstDisplay = true;

		function GetMonthName(monthNumber) {
			var months = ['leden', 'únor', 'březen', 'duben', 'květen', 'červen', 'červenec', 'srpen', 'září', 'říjen', 'listopad', 'prosinec'];
			return months[monthNumber - 1];
		}

		setMonth(monthNumber, mon, tue, wed, thur, fri, sat, sund);

		function setMonth(monthNumber, mon, tue, wed, thur, fri, sat, sund) {
			$('.month').text(GetMonthName(monthNumber) + ' ' + yearNumber);
			$('.month').attr('data-month', monthNumber);
			printDateNumber(monthNumber, mon, tue, wed, thur, fri, sat, sund);
		}

		$('.btn-next').on('click', function(e) {
			var monthNumber = $('.month').attr('data-month');
			if (monthNumber > 11) {
				$('.month').attr('data-month', '0');
				var monthNumber = $('.month').attr('data-month');
				yearNumber = yearNumber + 1;
				setMonth(parseInt(monthNumber) + 1, mon, tue, wed, thur, fri, sat, sund);
				return false;
			} else {
				setMonth(parseInt(monthNumber) + 1, mon, tue, wed, thur, fri, sat, sund);
				return false;
			};
		});

		$('.btn-prev').on('click', function(e) {
			var monthNumber = $('.month').attr('data-month');
			if (monthNumber < 2) {
				$('.month').attr('data-month', '13');
				var monthNumber = $('.month').attr('data-month');
				yearNumber = yearNumber - 1;
				setMonth(parseInt(monthNumber) - 1, mon, tue, wed, thur, fri, sat, sund);
				return false;
			} else {
				setMonth(parseInt(monthNumber) - 1, mon, tue, wed, thur, fri, sat, sund);
				return false;
			};
		});

		/**
		 * Get all dates for current month
		 */

		function printDateNumber(monthNumber, mon, tue, wed, thur, fri, sat, sund) {

			$($('tbody.event-calendar tr')).each(function(index) {
				$(this).empty();
			});

			$($('thead.event-days tr')).each(function(index) {
				$(this).empty();
			});

			function getDaysInMonth(month, year) {
				// Since no month has fewer than 28 days
				var date = new Date(year, month, 1);
				var days = [];
				while (date.getMonth() === month) {
    				var tmpArr = [];
      				tmpArr[0] = date.getDate();
      				tmpArr[1] = date.getDay();
      				days.push(tmpArr);
      				// days.push(new Date(date));
					date.setDate(date.getDate() + 1);
				}
				return days;
			}

			i = 0;

			setDaysInOrder(mon, tue, wed, thur, fri, sat, sund);

			function setDaysInOrder(mon, tue, wed, thur, fri, sat, sund) {
				var monthDay = getDaysInMonth(monthNumber - 1, yearNumber)[0].toString().substring(0, 3);
					$('thead.event-days tr').append('<td>' + mon + '</td><td>' + tue + '</td><td>' + wed + '</td><td>' + thur + '</td><td>' + fri + '</td><td>' + sat + '</td><td>' + sund + '</td>');
			};
			$(getDaysInMonth(monthNumber - 1, yearNumber)).each(function() {
			    var day = $(this)[0];
			    var week = $(this)[1];

			    if(firstDisplay == true){
			      for (var i = 0; i < firstDay; i++) {
			        $('tbody.event-calendar tr.1').append('<td date-month="' + '' + '" date-day="' + '' + '" date-year="' + '' + '">' + '</td>');
			      };
			      firstDisplay = false;
			    }

			    $('tbody.event-calendar tr.1').append('<td date-month="' + monthNumber + '" date-day="' + day + '" date-year="' + yearNumber + '">' + day + '</td>');
			  });

			  var date = new Date();
			  var month = date.getMonth() + 1;
			  var thisyear = new Date().getFullYear();
			  setCurrentDay(month, thisyear);
			  setEvent();
			  displayEvent();
		}

		/**
		 * Get current day and set as '.current-day'
		 */
		function setCurrentDay(month, year) {
			var viewMonth = $('.month').attr('data-month');
			var eventYear = $('.event-days').attr('date-year');
			if (parseInt(year) === yearNumber) {
				if (parseInt(month) === parseInt(viewMonth)) {
					$('tbody.event-calendar td[date-day="' + d.getDate() + '"]').addClass('current-day');
				}
			}
		};

		/**
		 * Add class '.active' on calendar date
		 */
		$(document).on('click', '.calendar tbody td', function(e) {
			console.log('test');
			if ($(this).hasClass('event')) {
				$('tbody.event-calendar td').removeClass('active');
				$(this).addClass('active');
				var monthEvent = $(this).attr('date-month');
				var dayEvent = $(this).text();
				$('.day-event[date-month="' + monthEvent + '"][date-day="' + dayEvent + '"]').slideDown('fast');
				var link = $('.day-event[date-month="' + monthEvent + '"][date-day="' + dayEvent + '"] .day_link').attr('href');
				console.log('test');
				window.location.href=link;
			} else {
				$('tbody.event-calendar td').removeClass('active');
			};
		});

		/**
		 * Add '.event' class to all days that has an event
		 */
		function setEvent() {
			$('.day-event').each(function(i) {
				var eventMonth = $(this).attr('date-month');
				var eventDay = $(this).attr('date-day');
				var eventYear = $(this).attr('date-year');
				var eventClass = $(this).attr('event-class');
				if (eventClass === undefined) eventClass = 'event';
				else eventClass = 'event ' + eventClass;

				if (parseInt(eventYear) === yearNumber) {
					$('tbody.event-calendar tr td[date-month="' + eventMonth + '"][date-day="' + eventDay + '"]').addClass(eventClass);
				}
			});
		};

		/**
		 * Get current day on click in calendar
		 * and find day-event to display
		 */
		function displayEvent() {
			$('tbody.event-calendar td').hover(function() {
				//$('.day-event').slideUp('fast');
				var monthEvent = $(this).attr('date-month');
				var dayEvent = $(this).text();
				$('.day-event[date-month="' + monthEvent + '"][date-day="' + dayEvent + '"]').slideDown('fast');
			}, function() {
   				$('.day-event').slideUp('fast');
			});
		};

		/**
		 * Close day-event
		 */
		$('.close').on('click', function(e) {
			$(this).parent().slideUp('fast');
			return false;
		});

		/**
		 * Save & Remove to/from personal list
		 */
		$('.save').click(function() {
			if (this.checked) {
				$(this).next().text('Remove from personal list');
				var eventHtml = $(this).closest('.day-event').html();
				var eventMonth = $(this).closest('.day-event').attr('date-month');
				var eventDay = $(this).closest('.day-event').attr('date-day');
				var eventNumber = $(this).closest('.day-event').attr('data-number');
				$('.person-list').append('<div class="day" date-month="' + eventMonth + '" date-day="' + eventDay + '" data-number="' + eventNumber + '" style="display:none;">' + eventHtml + '</div>');
				$('.day[date-month="' + eventMonth + '"][date-day="' + eventDay + '"]').slideDown('fast');
				$('.day').find('.close').remove();
				$('.day').find('.save').removeClass('save').addClass('remove');
				$('.day').find('.remove').next().addClass('hidden-print');
				remove();
				sortlist();
			} else {
				$(this).next().text('Save to personal list');
				var eventMonth = $(this).closest('.day-event').attr('date-month');
				var eventDay = $(this).closest('.day-event').attr('date-day');
				var eventNumber = $(this).closest('.day-event').attr('data-number');
				$('.day[date-month="' + eventMonth + '"][date-day="' + eventDay + '"][data-number="' + eventNumber + '"]').slideUp('slow');
				setTimeout(function() {
					$('.day[date-month="' + eventMonth + '"][date-day="' + eventDay + '"][data-number="' + eventNumber + '"]').remove();
				}, 1500);
			}
		});

		function remove() {
			$('.remove').click(function() {
				if (this.checked) {
					$(this).next().text('Remove from personal list');
					var eventMonth = $(this).closest('.day').attr('date-month');
					var eventDay = $(this).closest('.day').attr('date-day');
					var eventNumber = $(this).closest('.day').attr('data-number');
					$('.day[date-month="' + eventMonth + '"][date-day="' + eventDay + '"][data-number="' + eventNumber + '"]').slideUp('slow');
					$('.day-event[date-month="' + eventMonth + '"][date-day="' + eventDay + '"][data-number="' + eventNumber + '"]').find('.save').attr('checked', false);
					$('.day-event[date-month="' + eventMonth + '"][date-day="' + eventDay + '"][data-number="' + eventNumber + '"]').find('span').text('Save to personal list');
					setTimeout(function() {
						$('.day[date-month="' + eventMonth + '"][date-day="' + eventDay + '"][data-number="' + eventNumber + '"]').remove();
					}, 1500);
				}
			});
		}

		/**
		 * Sort personal list
		 */
		function sortlist() {
			var personList = $('.person-list');

			personList.find('.day').sort(function(a, b) {
				return +a.getAttribute('date-day') - +b.getAttribute('date-day');
			}).appendTo(personList);
		}

		/**
		 * Print button
		 */
		$('.print-btn').click(function() {
			window.print();
		});
  },

};

$(document).ready(function() {
	var d = new Date();

    n = d.getMonth() + 1;
    console.log(n);
    y = d.getFullYear();
	calendar.init(y,n);
});

});
`

And here you can find it on jsfiddle https://jsfiddle.net/franrcardenas/qc11y1rc/ to see it more clear.

Thanks,

**Comment by evocreative** [comment]
Hi,

Just to let you know that it seems that I have been able to fix this, you can see it in the jsfiddle:

https://jsfiddle.net/franrcardenas/qc11y1rc/

The only problem is for any strange reason is not working correctly on January 2017 month, so I needed to add a 'hack' for this month as something like:

`				if(strDate == '2017/1/1'){
					firstDay = 6;
				}else{
					firstDay = tmpDate.getDay() - 1;
				}
`

Thanks,
