### ISSUE TITLE
Next month is not displayed

### ISSUE THREAD

**Issue by Abdou00** [philipehsing/jQuery.Simple-Event-Calendar#18]
Hello,
I have a problem with my calendar when I change month, the console returns the following error:
"Uncaught TypeError: Cannot read property 'toString' of undefined"
Do you have any idea what is causing this problem? Thank you very much!!

**Comment by philipehsing** [comment]
Can i see it live?

**Comment by Abdou00** [comment]
Thank you for your answer. Yes you can at the following address: [http://wordpress.lepoles.com/evenements/](url)

**Comment by philipehsing** [comment]
N
