### ISSUE TITLE
Changing month and year

### ISSUE THREAD

**Issue by leandrow** [philipehsing/jQuery.Simple-Event-Calendar#3]
How can I to list days automatically based on month and year?

Thanks! :)

**Comment by philipehsing** [comment]
U can change month ? Do u want a function that change year?

**Comment by leandrow** [comment]
Yes! :)
I want a function that changes the year too.

**Comment by philipehsing** [comment]
user this " var yearNumber = (new Date).getFullYear(); " and just add + 1 in your year function

**Comment by leandrow** [comment]
Sorry. I don't know how to add this new feature in your code.
