### ISSUE TITLE
month does not start with monday.

### ISSUE THREAD

**Issue by gerrold** [philipehsing/jQuery.Simple-Event-Calendar#5]
the first day of the week is displayed to be the first day of the month. For example:
this august the first day is Saturday, so the calendar shows the days from Saturday till Friday, not starting from Monday. Even the example works this way. See it here:
https://www.dropbox.com/s/8agwyso03rnupoq/Clipboard01.jpg?dl=0
whats wrong?

**Comment by philipehsing** [comment]
The example img is not correct. 
You can modified the script file if you want :)
