### ISSUE TITLE
Need to define the passed date

### ISSUE THREAD

**Issue by tesshsu** [philipehsing/jQuery.Simple-Event-Calendar#9]
Hi, I just want to defind the passed date and it's not work at all, could you help? thanks a lot!!
here is my code:
 
        function setPassedDay(date) {
            var today = d.getDate();
                todayIndex = today.index();
                passIndex = todayIndex - 1;
                if( today > parseInt(d)) {
                    $(passIndex).each(function(index){
                         $(this).attr('.passed-day');
                    });
                }
    
            }
        };

**Comment by philipehsing** [comment]
Do you want to add a class to all dates before today?

**Comment by jennoefur** [comment]
Hello,

So tesshsu didn't reply but that's exactly what I want to do - add a class to all dates in the past.

Really like the calendar, thank you :)

**Comment by tesshsu** [comment]
Yes, that I want to do, the passed day before today, and add the passed date class: "state-disabled"
here is the entire code:
var calendar = {

    init: function (minDate) {

        var mon = 'Mon';
            tue = 'Tue';
            wed = 'Wed';
            thur = 'Thur';
            fri = 'Fri';
            sat = 'Sat';
            sund = 'Sun';
            minDate = minDate;   
        /**
         * Get current date
         */
        var d = new Date();
            strDate = d.getFullYear() + "/" + (d.getMonth() + 1) + "/" + d.getDate();

        /**
         * Get current month and set as '.current-month' in title
         */
        var monthNumber = d.getMonth() + 1;

        //get the current year and add attribute
         var year = d.getFullYear();
             cyear = $("<span></span>").text(year);

        function GetMonthName(monthNumber) {
            var months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
            return months[monthNumber - 1];
        }

        setMonth(monthNumber, mon, tue, wed, thur, fri, sat, sund);
        $('.day-event[date-month="' + monthNumber + '"][date-day="' + d.getDate() + '"]').slideDown('fast');

        function setMonth(monthNumber, mon, tue, wed, thur, fri, sat, sund) {
            $('.month').text(GetMonthName(monthNumber) + ".").append(cyear);
            $('.month').attr('data-month', monthNumber);
            printDateNumber(monthNumber, mon, tue, wed, thur, fri, sat, sund);
        }

        function setMminDate(mindate) {
            minDate = mindate;
        }

        $('.btn-next').on('click', function (e) {
            var monthNumber = $('.month').attr('data-month');
            if (monthNumber > 11) {
                $('.month').attr('data-month', '0');
                var monthNumber = $('.month').attr('data-month');
                setMonth(parseInt(monthNumber) + 1, mon, tue, wed, thur, fri, sat, sund);
                setEvent(parseInt(monthNumber) + 1);
            } else {
                setMonth(parseInt(monthNumber) + 1, mon, tue, wed, thur, fri, sat, sund);
                setEvent(parseInt(monthNumber) + 1);
            };            
        });

        $('.btn-prev').on('click', function (e) {
            var monthNumber = $('.month').attr('data-month');
            if (monthNumber < 2) {
                $('.month').attr('data-month', '13');
                var monthNumber = $('.month').attr('data-month');
                setMonth(parseInt(monthNumber) - 1, mon, tue, wed, thur, fri, sat, sund);
                setEvent(parseInt(monthNumber) - 1);
            } else {
                setMonth(parseInt(monthNumber) - 1, mon, tue, wed, thur, fri, sat, sund);
                setEvent(parseInt(monthNumber) - 1);
            };

        });

        /**
         * Get all dates for current month
         */

        function printDateNumber(monthNumber, mon, tue, wed, thur, fri, sat, sund) {

            $($('tbody.event-calendar tr')).each(function (index) {
                $(this).empty();
            });

            $($('thead.event-days tr')).each(function (index) {
                $(this).empty();
            });

            function getDaysInMonth(month, year) {
                // Since no month has fewer than 28 days
                var date = new Date(year, month, 1);
                var days = [];
                while (date.getMonth() === month) {
                    days.push(new Date(date));
                    date.setDate(date.getDate() + 1);
                }
                return days;
            }

            var yearNumber = (new Date).getFullYear();
            i = 0;

            setDaysInOrder(mon, tue, wed, thur, fri, sat, sund);

            function setDaysInOrder(mon, tue, wed, thur, fri, sat, sund) {
                var weeks = [sund, mon, tue, wed, thur, fri, sat];
                var cls = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];
                var firstDay = new Date(yearNumber, monthNumber - 1, 1);
                var w = firstDay.getDay();
                var count = 0;
                var html = '';
                while (count < 7) {
                    html += '<td class="' + cls[w] + '">' + weeks[w] + '</td>';
                    w = (w + 1) % 7;
                    count += 1;
                }
                $('thead.event-days tr').append(html);
            };
            $(getDaysInMonth(monthNumber - 1, yearNumber)).each(function (index) {
                var index = index + 1;
                additionnalClass = '';
                date = new Date(yearNumber, monthNumber-1, index, 0, 0, 0, 0);
                if( minDate !== undefined && date < minDate){
                    additionnalClass = 'state-disabled'
                }  			
                if (index < 8) {
                    $('tbody.event-calendar tr.1').append('<td class="' + additionnalClass  + '" date-month="' + monthNumber + '" date-day="' + index + '">' + index + '</td>');
                } else if (index < 15) {
                    $('tbody.event-calendar tr.2').append('<td class="' + additionnalClass  + '" date-month="' + monthNumber + '" date-day="' + index + '">' + index + '</td>');
                } else if (index < 22) {
                    $('tbody.event-calendar tr.3').append('<td class="' + additionnalClass  + '" date-month="' + monthNumber + '" date-day="' + index + '">' + index + '</td>');
                } else if (index < 29) {
                    $('tbody.event-calendar tr.4').append('<td class="' + additionnalClass  + '" date-month="' + monthNumber + '" date-day="' + index + '">' + index + '</td>');
                } else if (index < 32) {
                    $('tbody.event-calendar tr.5').append('<td class="' + additionnalClass  + '" date-month="' + monthNumber + '" date-day="' + index + '">' + index + '</td>');
                }
                i++;
            });
            var date = new Date();
            var month = date.getMonth() + 1;
            setCurrentDay(month);
            setPassedDay(month);
            setEvent(monthNumber);
            displayEvent();
            setActiveDay();
        }

        /**
         * Get current day and set as '.current-day'
         */
        function setCurrentDay(month) {
            var viewMonth = $('.month').attr('data-month');
            if (parseInt(month) === parseInt(viewMonth)) {
                $('tbody.event-calendar td[date-day="' + d.getDate() + '"]').addClass('current-day');
            }
        };
        /**
         * Get passed day and set as '.passed-day' add Tess
         */
        function setPassedDay(month) {
            var viewMonth = $('.month').attr('data-month');
            if (parseInt(month) < parseInt(viewMonth)){
                $('tbody.event-calendar td[date-day="' + d.getDate() + '"]').addClass('passed-day');
            }
        };
        /**
         * Add '.event' class to all days that has an event
         */
        function setEvent(month) {
            $('tbody.event-calendar tr td').removeClass('event');

            $('.day-event').each(function (i) {                
                var eventMonth = $(this).attr('date-month');
                var eventDay = $(this).attr('date-day');
                if (month != eventMonth) { return; }
                $('tbody.event-calendar tr td[date-month="' + eventMonth + '"][date-day="' + eventDay + '"]').addClass('event');
            });
        };
        /**
         * force passed event grey color
         */
        if( $(".state-disabled").hasClass("event")) {
            $(".state-disabled.event").css("color","#b5b5b5");
        }
        /**
         * force current event day white color
         */
        if($('.event-calendar tr td').hasClass('current-day')){
            $(this).css("color","#fff");
        }
        /**
         * Get current day on click in calendar
         * and find day-event to display
         */
        function displayEvent() {
            $('tbody.event-calendar td').on('click', function (e) {
                if ($(this).hasClass('event')) {
                    $('.day-event').slideUp('fast');
                    var monthEvent = $(this).attr('date-month');
                    var dayEvent = $(this).text();
                    $('.day-event[date-month="' + monthEvent + '"][date-day="' + dayEvent + '"]').slideDown('fast');
                    $('tbody.event-calendar td').removeClass('active');
                    $(this).addClass('active');
                    $('.calendar').attr('data-active-month', $(this).attr('date-month'))
                                  .attr('data-active-day', $(this).attr('date-day'));
                }
            });
        };

        function setActiveDay() {
            var activeMonth = $('.calendar').attr('data-active-month');
            var activeDay = $('.calendar').attr('data-active-day');
            if (activeMonth && activeDay) {
                $('tbody.event-calendar td.event[date-month="' + activeMonth + '"][date-day="' + activeDay + '"]').addClass('active');
            }
        }

        /**
         * Save & Remove to/from personal list
         */
        $('.save').click(function () {
            if (this.checked) {
                $(this).next().text('Remove from personal list');
                var eventHtml = $(this).closest('.day-event').html();
                var eventMonth = $(this).closest('.day-event').attr('date-month');
                var eventDay = $(this).closest('.day-event').attr('date-day');
                var eventNumber = $(this).closest('.day-event').attr('data-number');
                $('.person-list').append('<div class="day" date-month="' + eventMonth + '" date-day="' + eventDay + '" data-number="' + eventNumber + '" style="display:none;">' + eventHtml + '</div>');
                $('.day[date-month="' + eventMonth + '"][date-day="' + eventDay + '"]').slideDown('fast');
                $('.day').find('.close').remove();
                $('.day').find('.save').removeClass('save').addClass('remove');
                $('.day').find('.remove').next().addClass('hidden-print');
                remove();
                sortlist();
            } else {
                $(this).next().text('Save to personal list');
                var eventMonth = $(this).closest('.day-event').attr('date-month');
                var eventDay = $(this).closest('.day-event').attr('date-day');
                var eventNumber = $(this).closest('.day-event').attr('data-number');
                $('.day[date-month="' + eventMonth + '"][date-day="' + eventDay + '"][data-number="' + eventNumber + '"]').slideUp('slow');
                setTimeout(function () {
                    $('.day[date-month="' + eventMonth + '"][date-day="' + eventDay + '"][data-number="' + eventNumber + '"]').remove();
                }, 1500);
            }
        });

        function remove() {
            $('.remove').click(function () {
                if (this.checked) {
                    $(this).next().text('Remove from personal list');
                    var eventMonth = $(this).closest('.day').attr('date-month');
                    var eventDay = $(this).closest('.day').attr('date-day');
                    var eventNumber = $(this).closest('.day').attr('data-number');
                    $('.day[date-month="' + eventMonth + '"][date-day="' + eventDay + '"][data-number="' + eventNumber + '"]').slideUp('slow');
                    $('.day-event[date-month="' + eventMonth + '"][date-day="' + eventDay + '"][data-number="' + eventNumber + '"]').find('.save').attr('checked', false);
                    $('.day-event[date-month="' + eventMonth + '"][date-day="' + eventDay + '"][data-number="' + eventNumber + '"]').find('span').text('Save to personal list');
                    setTimeout(function () {
                        $('.day[date-month="' + eventMonth + '"][date-day="' + eventDay + '"][data-number="' + eventNumber + '"]').remove();
                    }, 1500);
                }
            });
        }

        /**
         * Sort personal list
         */
        function sortlist() {
            var personList = $('.person-list');

            personList.find('.day').sort(function (a, b) {
                return +a.getAttribute('date-day') - +b.getAttribute('date-day');
            }).appendTo(personList);
        }

        /**
         * Print button
         */
        $('.print-btn').click(function () {
            window.print();
        });

    },
};

$(document).ready(function () {
	var today =  new Date();
    calendar.init(new Date(today.getFullYear(), today.getMonth(), today.getDate(),0,0,0,0));
});
